

version: '3'

services:
  backend:
    build: .
    container_name: backend
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - .:/codes
    ports:
      - "3000:3000"
    working_dir: /frontend
